DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS users;

CREATE TABLE chat (
    postId INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    userId INTEGER NOT NULL,
    name TEXT NOT NULL,
    sent TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    pwHash TEXT NOT NULL,
    email TEXT,
    confirmed INTEGER
);