DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS USER;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE USER{
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Salt since time is RANDOM
    NAME TEXT NOT NULL,
    pwHash TEXT NOT NULL,
}