/*
This file can help you to test the api locally by installing the httpBook extensions in VScode. 
The password of Alice is 12345678.
*/
POST http://127.0.0.1:5000/api/chat/send
Content-Type: application/json

{"name": "Alice","postId": 1, "userID":2,"content": "yoooooo", "pwHash":"73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8="
}

HTTP/1.1 200  - OK
server: Werkzeug/2.2.2 Python/3.9.5
date: Mon, 17 Apr 2023 01:58:29 GMT
content-type: application/json
content-length: 14
access-control-allow-origin: *
connection: close
###
POST http://127.0.0.1:5000/api/chat/getupdate
Content-Type: application/json

{"name": "Alice","postId": 1, "userID":2,"content": "yoooooo", "pwHash":"73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8="
}

HTTP/1.1 200  - OK
server: Werkzeug/2.2.2 Python/3.9.5
date: Mon, 17 Apr 2023 01:58:35 GMT
content-type: application/json
content-length: 323
access-control-allow-origin: *
connection: close
###
POST  http://localhost:5000/api/signup
Content-Type: application/json

{"name": "Alice","pwHash": "73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8="}

HTTP/1.1 200  - OK
server: Werkzeug/2.2.2 Python/3.9.5
date: Mon, 17 Apr 2023 00:33:55 GMT
content-type: application/json
content-length: 16
access-control-allow-origin: *
connection: close
###
POST  http://localhost:5000/api/login
Content-Type: application/json

{"name": "Alice","pwHash": "73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8=", "SECRET_KEY": "COMP3334group30Spring2023"}

HTTP/1.1 200  - OK
server: Werkzeug/2.2.2 Python/3.9.5
date: Mon, 17 Apr 2023 01:57:48 GMT
content-type: application/json
content-length: 270
access-control-allow-origin: *
connection: close