/*
This file can help you to test the api locally by installing the httpBook extensions in VScode. 
The password of Alice is 12345678.
*/
POST  http://localhost:5000/api/signup
Content-Type: application/json

{"name": "Alice","password": "73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8="}

HTTP/1.1 200  - OK
server: Werkzeug/2.2.2 Python/3.9.5
date: Thu, 13 Apr 2023 08:58:52 GMT
content-type: application/json
content-length: 18
access-control-allow-origin: *
connection: close
###
POST  http://localhost:5000/api/login
Content-Type: application/json

{"name": "Alice","password": "73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8=", "SECRET_KEY": "COMP3334group30Spring2023"}

HTTP/1.1 200  - OK
server: Werkzeug/2.2.2 Python/3.9.5
date: Sun, 16 Apr 2023 08:40:17 GMT
content-type: application/json
content-length: 190
access-control-allow-origin: *
connection: close