DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE USER{
    userName INTEGER PRIMARY KEY AUTOINCREMENT,
    pw TEXT NOT NULL,
    content TEXT NOT NULL
}